window.SGO_SHOWCASE = {
  "meta": {
    "title": "SGO-Audit",
    "tagline": "Finds crash reports whose automation labels do not line up with the rest of the public record.",
    "data_vintage": "Archive-2021-2025",
    "generated_at_utc": "2026-07-23T23:39:32.410062+00:00",
    "responsible_use": "Consensus rows are review candidates only. Multiple methods disagreeing with the reported label raises review priority; it is not a confirmed misclassification, safety ranking, or safety-rate claim.",
    "repo_url": "https://github.com/nktarasios/ADAS"
  },
  "corpus": {
    "ads_clean": 1899,
    "adas_clean": 2690,
    "combined": 4589
  },
  "signals": {
    "heuristic_flags": 37,
    "classifier_flags": 20,
    "phase2_sample": 50,
    "consensus_queue": 66,
    "phase2_disagrees": 9
  },
  "operating_point": {
    "model": "lightgbm",
    "threshold": 0.59,
    "precision": 0.9119170984455959,
    "recall": 0.3776824034334764,
    "rationale": "Selected the threshold that meets the synthetic mislabel precision target of 80%, maximizing recall within that precision constraint.",
    "calibration": "none",
    "target_precision": 0.8
  },
  "disagreement": {
    "all_agree": 41,
    "only_one_method_available": 0,
    "phase1_phase2_agree_vs_reported": 0,
    "phase1_phase2_disagree": 9
  },
  "tiers": {
    "single_signal": 66,
    "three_signal_consensus": 0,
    "two_signal_consensus": 0
  },
  "validation": {
    "reference_ids": 13,
    "present": 7,
    "missing": 6,
    "overlaps": {
      "heuristic_flags": 0,
      "classifier_flagged_records": 0,
      "phase1_phase2_agree_vs_reported": 0
    },
    "caveats": [
      "The validation sample is small and manually extracted from published ODI resumes.",
      "The named ODI records are crashes scrutinized for FSD reduced-visibility performance, not labels proving automation-level misclassification.",
      "Overlap between flags and ODI-named records is a directional review signal, not statistical proof.",
      "Missing recent IDs may reflect the current Archive-2021-2025 data snapshot vintage rather than an error."
    ]
  },
  "entity_counts": [
    [
      "Waymo LLC",
      8
    ],
    [
      "Tesla, Inc.",
      7
    ],
    [
      "Zoox, Inc.",
      6
    ],
    [
      "Apple Inc.",
      3
    ],
    [
      "Pony.ai",
      3
    ],
    [
      "VinFast Auto, LLC",
      3
    ],
    [
      "Lucid USA, Inc.",
      3
    ],
    [
      "TORC Robotics, Inc.",
      2
    ],
    [
      "WeRide Corp",
      2
    ],
    [
      "Daimler Trucks North America, LLC",
      2
    ],
    [
      "Ford Motor Company",
      2
    ],
    [
      "Hyundai Motor America",
      2
    ]
  ],
  "queue": [
    {
      "report_id": "30270-11019",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": false,
      "phase2": true,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9999405918783478,
      "phase2_pred": "Level 2 ADAS",
      "rules": "",
      "category": "phase1_phase2_disagree"
    },
    {
      "report_id": "30270-7159",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9999369528272457,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged",
      "category": ""
    },
    {
      "report_id": "30531-1984",
      "entity": "Transdev Alternative Services",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9999276790309142,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged",
      "category": ""
    },
    {
      "report_id": "30610-10473",
      "entity": "Zoox, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": false,
      "phase2": true,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9999238778229758,
      "phase2_pred": "Level 2 ADAS",
      "rules": "",
      "category": "phase1_phase2_disagree"
    },
    {
      "report_id": "30270-11066",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": false,
      "phase2": true,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9999219793037478,
      "phase2_pred": "Level 2 ADAS",
      "rules": "",
      "category": "phase1_phase2_disagree"
    },
    {
      "report_id": "30270-11016",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": false,
      "phase2": true,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9999205073013424,
      "phase2_pred": "Level 2 ADAS",
      "rules": "",
      "category": "phase1_phase2_disagree"
    },
    {
      "report_id": "30270-10964",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": false,
      "phase2": true,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9999154228529402,
      "phase2_pred": "Level 2 ADAS",
      "rules": "",
      "category": "phase1_phase2_disagree"
    },
    {
      "report_id": "30270-10969",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": false,
      "phase2": true,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9999063564394863,
      "phase2_pred": "Level 2 ADAS",
      "rules": "",
      "category": "phase1_phase2_disagree"
    },
    {
      "report_id": "30410-5003",
      "entity": "Motional",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9998976176889115,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged",
      "category": ""
    },
    {
      "report_id": "30530-4264",
      "entity": "Aurora Operations, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9998880132351687,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged",
      "category": ""
    },
    {
      "report_id": "30590-3431",
      "entity": "Apple Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.999877584643328,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30610-2227",
      "entity": "Zoox, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9998695946595032,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged",
      "category": ""
    },
    {
      "report_id": "30330-3561",
      "entity": "TORC Robotics, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.99983744547548,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30792-9317",
      "entity": "WeRide Corp",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.999810491965591,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "13781-9861",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9997944867545552,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "30290-3347",
      "entity": "Argo AI",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9997921941267673,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "12381-3557",
      "entity": "Daimler Trucks North America, LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9997885110627159,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30711-7649",
      "entity": "Pony.ai",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9997720678667129,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "30711-6431",
      "entity": "Pony.ai",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9997443156567551,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "502-3416",
      "entity": "Ford Motor Company",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9997240218791296,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30270-10923",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": false,
      "phase2": true,
      "phase1_pred": "ADS",
      "phase1_conf": 0.999720977092835,
      "phase2_pred": "Level 2 ADAS",
      "rules": "",
      "category": "phase1_phase2_disagree"
    },
    {
      "report_id": "30270-10660",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": false,
      "phase2": true,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9996629674324051,
      "phase2_pred": "Level 2 ADAS",
      "rules": "",
      "category": "phase1_phase2_disagree"
    },
    {
      "report_id": "30610-4217",
      "entity": "Zoox, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9995706023556032,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30412-8748",
      "entity": "Cruise LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9994714490711976,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30391-8984",
      "entity": "Kodiak Robotics",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9994017642449498,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "988-9101",
      "entity": "PACCAR Incorporated",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9994017642449498,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30792-1699",
      "entity": "WeRide Corp",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9992308777301134,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "12381-3438",
      "entity": "Daimler Trucks North America, LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9985938522825857,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30711-7848",
      "entity": "Pony.ai",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9984969432966663,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged; ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30791-10003",
      "entity": "AutoX Technologies Inc",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9984473972048123,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30690-4793",
      "entity": "Robotic Research",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9980759546733957,
      "phase2_pred": null,
      "rules": "ads_label_but_consumer_driver",
      "category": ""
    },
    {
      "report_id": "30590-1482",
      "entity": "Apple Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9978846548628104,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "669-1762",
      "entity": "Hyundai Motor America",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "Level 2 ADAS",
      "phase1_conf": 0.9959400892703687,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "33257-8867",
      "entity": "VinFast Auto, LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9957711355282568,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged; ads_label_but_consumer_driver",
      "category": ""
    },
    {
      "report_id": "33257-8638",
      "entity": "VinFast Auto, LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9956576906891967,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged; ads_label_but_consumer_driver",
      "category": ""
    },
    {
      "report_id": "30330-3482",
      "entity": "TORC Robotics, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9947564567364393,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "540-6944",
      "entity": "General Motors, LLC",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9945386730536815,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "30291-10128",
      "entity": "Nuro",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9943801928188997,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "273-2632",
      "entity": "Chrysler (FCA US, LLC)",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9939837241668265,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged; ads_label_but_consumer_driver",
      "category": ""
    },
    {
      "report_id": "30610-10294",
      "entity": "Zoox, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": false,
      "phase2": true,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9927206384741182,
      "phase2_pred": "Level 2 ADAS",
      "rules": "",
      "category": "phase1_phase2_disagree"
    },
    {
      "report_id": "10003-2932",
      "entity": "Navistar, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9922781966096879,
      "phase2_pred": null,
      "rules": "ads_label_but_consumer_driver",
      "category": ""
    },
    {
      "report_id": "502-10412",
      "entity": "Ford Motor Company",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9919950994248787,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "30415-1317",
      "entity": "NAVYA Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9912825790056609,
      "phase2_pred": null,
      "rules": "ads_label_but_consumer_driver",
      "category": ""
    },
    {
      "report_id": "30610-5224",
      "entity": "Zoox, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.989987261285875,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30413-9958",
      "entity": "May Mobility",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.985809906750462,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "30590-6382",
      "entity": "Apple Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9856118556692833,
      "phase2_pred": null,
      "rules": "ads_narrative_level2_language",
      "category": ""
    },
    {
      "report_id": "28349-8482",
      "entity": "Lucid USA, Inc.",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9855492960496499,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "753-7780",
      "entity": "Kia America, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9762050098938292,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged; ads_label_but_consumer_driver",
      "category": ""
    },
    {
      "report_id": "28349-5694",
      "entity": "Lucid USA, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9758463885301691,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged; ads_label_but_consumer_driver",
      "category": ""
    },
    {
      "report_id": "13781-7574",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9755368486377328,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "33257-8085",
      "entity": "VinFast Auto, LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9707518485068478,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged",
      "category": ""
    },
    {
      "report_id": "540-6884",
      "entity": "General Motors, LLC",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9689511719111906,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "30610-2151",
      "entity": "Zoox, Inc.",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9686865513087177,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged",
      "category": ""
    },
    {
      "report_id": "855-9284",
      "entity": "Mercedes-Benz USA, LLC",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9667261818337629,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "13781-10735",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9553757956298359,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "29990-9652",
      "entity": "Rivian Automotive, LLC",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9198008817930128,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "10561-8671",
      "entity": "APTIV",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9183764724224867,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "669-5206",
      "entity": "Hyundai Motor America",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9167298987869761,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged",
      "category": ""
    },
    {
      "report_id": "13781-7197",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9150239027731955,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "29990-10074",
      "entity": "Rivian Automotive, LLC",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.9008972544437064,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "13781-9731",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.8614895473022759,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "13781-10132",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.8582090828038571,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "13781-7638",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.8333557789230994,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "1422-4087",
      "entity": "Volvo Car USA, LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": true,
      "phase1": false,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.80898528709763,
      "phase2_pred": null,
      "rules": "ads_file_but_adas_engaged",
      "category": ""
    },
    {
      "report_id": "28349-1805",
      "entity": "Lucid USA, Inc.",
      "reported": "Level 2 ADAS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "ADS",
      "phase1_conf": 0.7591689249998573,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    },
    {
      "report_id": "855-3183",
      "entity": "Mercedes-Benz USA, LLC",
      "reported": "ADS",
      "score": 1,
      "tier": "single_signal",
      "heuristic": false,
      "phase1": true,
      "phase2": false,
      "phase1_pred": "Level 2 ADAS",
      "phase1_conf": 0.6309748103918666,
      "phase2_pred": null,
      "rules": "",
      "category": ""
    }
  ],
  "classifier_flags": [
    {
      "report_id": "13781-9861",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9997944867545552
    },
    {
      "report_id": "30711-7649",
      "entity": "Pony.ai",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9997720678667129
    },
    {
      "report_id": "669-1762",
      "entity": "Hyundai Motor America",
      "reported": "ADS",
      "predicted": "Level 2 ADAS",
      "confidence": 0.9959400892703687
    },
    {
      "report_id": "540-6944",
      "entity": "General Motors, LLC",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9945386730536815
    },
    {
      "report_id": "30291-10128",
      "entity": "Nuro",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9943801928188997
    },
    {
      "report_id": "502-10412",
      "entity": "Ford Motor Company",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9919950994248787
    },
    {
      "report_id": "28349-8482",
      "entity": "Lucid USA, Inc.",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9855492960496499
    },
    {
      "report_id": "13781-7574",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9755368486377328
    },
    {
      "report_id": "540-6884",
      "entity": "General Motors, LLC",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9689511719111906
    },
    {
      "report_id": "855-9284",
      "entity": "Mercedes-Benz USA, LLC",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9667261818337629
    },
    {
      "report_id": "13781-10735",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9553757956298359
    },
    {
      "report_id": "29990-9652",
      "entity": "Rivian Automotive, LLC",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9198008817930128
    },
    {
      "report_id": "10561-8671",
      "entity": "APTIV",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9183764724224867
    },
    {
      "report_id": "13781-7197",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9150239027731955
    },
    {
      "report_id": "29990-10074",
      "entity": "Rivian Automotive, LLC",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.9008972544437064
    },
    {
      "report_id": "13781-9731",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.8614895473022759
    },
    {
      "report_id": "13781-10132",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.8582090828038571
    },
    {
      "report_id": "13781-7638",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.8333557789230994
    },
    {
      "report_id": "28349-1805",
      "entity": "Lucid USA, Inc.",
      "reported": "Level 2 ADAS",
      "predicted": "ADS",
      "confidence": 0.7591689249998573
    },
    {
      "report_id": "855-3183",
      "entity": "Mercedes-Benz USA, LLC",
      "reported": "ADS",
      "predicted": "Level 2 ADAS",
      "confidence": 0.6309748103918666
    }
  ],
  "demo_cases": [
    {
      "id": "30270-7159",
      "kind": "rule_only",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "summary": "Public SGO report 30270-7159. Reported automation level: ADS.",
      "rule": {
        "disagrees": true,
        "plain": "Filed as ADS, but the engagement field looks like Level 2 ADAS."
      },
      "model": {
        "disagrees": false,
        "predicted": "ADS",
        "confidence": 0.9999369528272457,
        "plain": "Structured ML model agrees with the reported label."
      },
      "llm": {
        "disagrees": false,
        "predicted": null,
        "plain": "No Phase-2 narrative disagreement available/used here."
      },
      "verdict_plain": "1 of 3 checks disagree with the reported label → queued for human review (not a confirmed error)."
    },
    {
      "id": "30270-11019",
      "kind": "llm_only",
      "entity": "Waymo LLC",
      "reported": "ADS",
      "summary": "Public SGO report 30270-11019. Reported automation level: ADS.",
      "rule": {
        "disagrees": false,
        "plain": "No rule disagreement on this record."
      },
      "model": {
        "disagrees": false,
        "predicted": "ADS",
        "confidence": 0.9999405918783478,
        "plain": "Structured ML model agrees with the reported label."
      },
      "llm": {
        "disagrees": true,
        "predicted": "Level 2 ADAS",
        "plain": "Local LLM narrative reader infers a different automation behavior from the crash narrative than the reported label."
      },
      "verdict_plain": "1 of 3 checks disagree with the reported label → queued for human review (not a confirmed error)."
    },
    {
      "id": "13781-9861",
      "kind": "model_flag",
      "entity": "Tesla, Inc.",
      "reported": "Level 2 ADAS",
      "summary": "Public SGO report 13781-9861. Reported automation level: Level 2 ADAS.",
      "rule": {
        "disagrees": false,
        "plain": "No rule disagreement on this record."
      },
      "model": {
        "disagrees": true,
        "predicted": "ADS",
        "confidence": 0.9997944867545552,
        "plain": "Structured ML model (LightGBM) predicts a different automation level from the reported label at high confidence."
      },
      "llm": {
        "disagrees": false,
        "predicted": null,
        "plain": "No Phase-2 narrative disagreement available/used here."
      },
      "verdict_plain": "1 of 3 checks disagree with the reported label → queued for human review (not a confirmed error)."
    },
    {
      "id": "demo-agree",
      "kind": "agreement",
      "entity": "Illustrative example",
      "reported": "ADS",
      "summary": "Teaching example: an ADS-labeled report whose fields, model prediction, and narrative all point the same way.",
      "rule": {
        "disagrees": false,
        "plain": "Rule checker finds no hard inconsistency."
      },
      "model": {
        "disagrees": false,
        "predicted": "ADS",
        "confidence": 0.99,
        "plain": "ML model also predicts ADS — agrees with the label."
      },
      "llm": {
        "disagrees": false,
        "predicted": "ADS",
        "plain": "Narrative reader also infers ADS behavior."
      },
      "verdict_plain": "0 of 3 checks disagree → not added to the review queue."
    }
  ],
  "tools_plain": [
    {
      "id": "rules",
      "name": "Rule checker",
      "does": "Looks for hard contradictions in structured fields and wording.",
      "example": "Labeled ADS, but narrative says the driver was supervising a Level-2 system."
    },
    {
      "id": "model",
      "name": "ML model (LightGBM)",
      "does": "Predicts ADS vs Level 2 ADAS from structured fields, then flags high-confidence disagreements.",
      "example": "Model is ~99% sure the record looks like ADS, but the file says Level 2 ADAS."
    },
    {
      "id": "llm",
      "name": "Local LLM narrative reader",
      "does": "Reads the crash narrative and independently infers the automation behavior described.",
      "example": "Narrative sounds like driver-supervised assist, while the label says ADS."
    },
    {
      "id": "fusion",
      "name": "Consensus queue",
      "does": "Combines the three checks and ranks records where more checks disagree.",
      "example": "2 or 3 disagreements → higher review priority. Still not a verdict."
    }
  ]
};
